modified:   .github/workflows/hugo.yaml

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -13,8 +13,8 @@ jobs:
             
             - uses: actions/checkout@v2
               with:
-                submodules: true  # Fetch Hugo themes (true OR recursive)
-                fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
+                submodules: true
+                fetch-depth: 0
 
             - name: Setup Hugo
               uses: peaceiris/actions-hugo@v2
@@ -24,6 +24,13 @@ jobs:
 
             - name: Build
               run: hugo --minify
+
+            - name: Check build errors
+              run: |
+                if [ $? -ne 0 ]; then
+                  echo "Build failed!"
+                  exit 1
+                fi
 
             - name: Deploy
               uses: nekitcorp/yandex-storage-website-action@v1
